const services = [
  {
    id: 1,
    title: "Fizjoterapia uroginekologiczna",
    date: "03-12-2022 - 20min",
    description:
      "Fusce fermentum et augue quis porta. Aenean interdum tincidunt posuere. Sed sed purus varius, tempus enim eu, lacinia mauris.",
    text: "Vestibulum sem enim, dictum eu diam sed, vulputate ultrices sem. Nullam nec lacus turpis. Fusce fermentum et augue quis porta. Aenean interdum tincidunt posuere. Sed sed purus varius, tempus enim eu, lacinia mauris. Pellentesque ac lacus dignissim, ultrices magna sit amet, pretium eros. Integer eget feugiat odio. Suspendisse aliquet a eros in auctor. Sed fermentum blandit massa nec imperdiet. Proin eu nisl libero. Morbi sit amet lectus aliquet, aliquam erat ac, rhoncus justo. Sed vestibulum, metus ut dapibus convallis, purus felis pretium metus, sit amet blandit felis nisi vel neque. In ac purus risus. Vivamus at erat mi. Nullam blandit sapien mi, quis congue lacus sollicitudin quis. Nunc eget velit auctor diam maximus fermentum. In lorem felis, sollicitudin et tincidunt eu, porttitor ac dui. Quisque condimentum, lacus ac ultricies dignissim, tortor magna condimentum eros, nec sagittis erat elit nec leo. Sed viverra tincidunt ante ac maximus. Cras sed leo tortor. Sed ultricies interdum est, ac hendrerit tortor blandit eget. In faucibus varius leo, in ornare lacus rutrum eu. Praesent quis ex non elit rhoncus tempor ac vitae velit. Curabitur placerat lacus et massa tempor ullamcorper. Nulla molestie condimentum nibh, a ullamcorper arcu tempus vitae. Aenean in mi viverra turpis posuere convallis a eget elit. Cras tristique sapien et ipsum feugiat consectetur. Cras ac ornare massa, sed dictum tortor. Duis ac vehicula quam. Pellentesque non sollicitudin ex. Proin ut porttitor nunc, non tempus sapien. Aenean maximus metus eget enim suscipit dignissim. In eu rhoncus eros. Proin condimentum facilisis diam quis suscipit. Quisque varius libero imperdiet enim porttitor lacinia nec vitae nibh. Mauris nulla turpis, dapibus ut erat et, lobortis lobortis diam. Donec fringilla lorem vel lacus iaculis vulputate. Sed sagittis libero ut augue pharetra, non fermentum ante ultrices. Vivamus ut tempus metus, vel congue lacus. Quisque varius libero imperdiet enim porttitor lacinia nec vitae nibh"
  },
  {
    id: 2,
    title: "Aenean interdum tincidunt posuere.",
    date: "03-12-2022 - 10min",
    description:
      "Fusce fermentum et augue quis porta. Aenean interdum tincidunt posuere. Sed sed purus varius, tempus enim eu, lacinia mauris.Aenean interdum tincidunt posuere.",
    text: "Sed sed purus varius, tempus enim eu, lacinia mauris. Pellentesque ac lacus dignissim, ultrices magna sit amet, pretium eros. Integer eget feugiat odio. Suspendisse aliquet a eros in auctor. Sed fermentum blandit massa nec imperdiet. Proin eu nisl libero. Morbi sit amet lectus aliquet, aliquam erat ac, rhoncus justo. Sed vestibulum, metus ut dapibus convallis, purus felis pretium metus, sit amet blandit felis nisi vel neque. In ac purus risus. Vivamus at erat mi. Nullam blandit sapien mi, quis congue lacus sollicitudin quis. Nunc eget velit auctor diam maximus fermentum. In lorem felis, sollicitudin et tincidunt eu, porttitor ac dui. Quisque condimentum, lacus ac ultricies dignissim, tortor magna condimentum eros, nec sagittis erat elit nec leo. Sed viverra tincidunt ante ac maximus. Cras sed leo tortor. Sed ultricies interdum est, ac hendrerit tortor blandit eget. In faucibus varius leo, in ornare lacus rutrum eu. Praesent quis ex non elit rhoncus tempor ac vitae velit. Curabitur placerat lacus et massa tempor ullamcorper. Nulla molestie condimentum nibh, a ullamcorper arcu tempus vitae. Aenean in mi viverra turpis posuere convallis a eget elit. Cras tristique sapien et ipsum feugiat consectetur. Cras ac ornare massa, sed dictum tortor. Duis ac vehicula quam. Pellentesque non sollicitudin ex. Proin ut porttitor nunc, non tempus sapien. Aenean maximus metus eget enim suscipit dignissim. In eu rhoncus eros. Proin condimentum facilisis diam quis suscipit. Quisque varius libero imperdiet enim porttitor lacinia nec vitae nibh. Mauris nulla turpis, dapibus ut erat et, lobortis lobortis diam. Donec fringilla lorem vel lacus iaculis vulputate. Sed sagittis libero ut augue pharetra, non fermentum ante ultrices. Vivamus ut tempus metus, vel congue lacus.",
  },
  {
    id: 3,
    title: "Fizjoterapia ortopedyczna",
    date: "03-12-2022 - 5min",
    description:
      "Fusce fermentum et augue quis porta. Aenean interdum tincidunt posuere. Sed sed purus varius, tempus enim eu, lacinia mauris.",
    text: "Vestibulum sem enim, dictum eu diam sed, vulputate ultrices sem. Nullam nec lacus turpis. Fusce fermentum et augue quis porta. Aenean interdum tincidunt posuere. Sed sed purus varius, tempus enim eu, lacinia mauris. Pellentesque ac lacus dignissim, ultrices magna sit amet, pretium eros. Integer eget feugiat odio. Suspendisse aliquet a eros in auctor. Sed fermentum blandit massa nec imperdiet. Proin eu nisl libero. Morbi sit amet lectus aliquet, aliquam erat ac, rhoncus justo. Sed vestibulum, metus ut dapibus convallis, purus felis pretium metus, sit amet blandit felis nisi vel neque. In ac purus risus. Vivamus at erat mi. Nullam blandit sapien mi, quis congue lacus sollicitudin quis. Nunc eget velit auctor diam maximus fermentum. In lorem felis, sollicitudin et tincidunt eu, porttitor ac dui. Quisque condimentum, lacus ac ultricies dignissim, tortor magna condimentum eros, nec sagittis erat elit nec leo. Sed viverra tincidunt ante ac maximus. Cras sed leo tortor. Sed ultricies interdum est, ac hendrerit tortor blandit eget. In faucibus varius leo, in ornare lacus rutrum eu. Praesent quis ex non elit rhoncus tempor ac vitae velit. Curabitur placerat lacus et massa tempor ullamcorper. Nulla molestie condimentum nibh, a ullamcorper arcu tempus vitae. Aenean in mi viverra turpis posuere convallis a eget elit. Cras tristique sapien et ipsum feugiat consectetur. Cras ac ornare massa, sed dictum tortor. Duis ac vehicula quam. Pellentesque non sollicitudin ex. Proin ut porttitor nunc, non tempus sapien. Aenean maximus metus eget enim suscipit dignissim. In eu rhoncus eros. Proin condimentum facilisis diam quis suscipit.",
  },
  {
    id: 4,
    title: "Quisque condimentum",
    date: "03-12-2022 - 5min",
    description:
      "Fusce fermentum et augue quis porta. Aenean interdum tincidunt posuere. Sed sed purus varius, tempus enim eu, lacinia mauris.",
    text: "Vestibulum sem enim, dictum eu diam sed, vulputate ultrices sem. Nullam nec lacus turpis. Fusce fermentum et augue quis porta. Aenean interdum tincidunt posuere. Sed sed purus varius, tempus enim eu, lacinia mauris. Pellentesque ac lacus dignissim, ultrices magna sit amet, pretium eros. Integer eget feugiat odio. Suspendisse aliquet a eros in auctor. Sed fermentum blandit massa nec imperdiet. Proin eu nisl libero. Morbi sit amet lectus aliquet, aliquam erat ac, rhoncus justo. Sed vestibulum, metus ut dapibus convallis, purus felis pretium metus, sit amet blandit felis nisi vel neque. In ac purus risus. Vivamus at erat mi. Nullam blandit sapien mi, quis congue lacus sollicitudin quis. Nunc eget velit auctor diam maximus fermentum. In lorem felis, sollicitudin et tincidunt eu, porttitor ac dui. Quisque condimentum, lacus ac ultricies dignissim, tortor magna condimentum eros, nec sagittis erat elit nec leo. Sed viverra tincidunt ante ac maximus. Cras sed leo tortor. Sed ultricies interdum est, ac hendrerit tortor blandit eget. In faucibus varius leo, in ornare lacus rutrum eu. Praesent quis ex non elit rhoncus tempor ac vitae velit. Curabitur placerat lacus et massa tempor ullamcorper. Nulla molestie condimentum nibh, a ullamcorper arcu tempus vitae. Aenean in mi viverra turpis posuere convallis a eget elit. Cras tristique sapien et ipsum feugiat consectetur. Cras ac ornare massa, sed dictum tortor. Duis ac vehicula quam. Pellentesque non sollicitudin ex. Proin ut porttitor nunc, non tempus sapien. Aenean maximus metus eget enim suscipit dignissim. In eu rhoncus eros. Proin condimentum facilisis diam quis suscipit.",
  },
  {
    id: 5,
    title: "Fizjoterapia ortopedyczna",
    date: "03-12-2022 - 5min",
    description:
      "Fusce fermentum et augue quis porta. Aenean interdum tincidunt posuere. Sed sed purus varius, tempus enim eu, lacinia mauris.",
    text: "Vestibulum sem enim, dictum eu diam sed, vulputate ultrices sem. Nullam nec lacus turpis. Fusce fermentum et augue quis porta. Aenean interdum tincidunt posuere. Sed sed purus varius, tempus enim eu, lacinia mauris. Pellentesque ac lacus dignissim, ultrices magna sit amet, pretium eros. Integer eget feugiat odio. Suspendisse aliquet a eros in auctor. Sed fermentum blandit massa nec imperdiet. Proin eu nisl libero. Morbi sit amet lectus aliquet, aliquam erat ac, rhoncus justo. Sed vestibulum, metus ut dapibus convallis, purus felis pretium metus, sit amet blandit felis nisi vel neque. In ac purus risus. Vivamus at erat mi. Nullam blandit sapien mi, quis congue lacus sollicitudin quis. Nunc eget velit auctor diam maximus fermentum. In lorem felis, sollicitudin et tincidunt eu, porttitor ac dui. Quisque condimentum, lacus ac ultricies dignissim, tortor magna condimentum eros, nec sagittis erat elit nec leo. Sed viverra tincidunt ante ac maximus. Cras sed leo tortor. Sed ultricies interdum est, ac hendrerit tortor blandit eget. In faucibus varius leo, in ornare lacus rutrum eu. Praesent quis ex non elit rhoncus tempor ac vitae velit. Curabitur placerat lacus et massa tempor ullamcorper. Nulla molestie condimentum nibh, a ullamcorper arcu tempus vitae. Aenean in mi viverra turpis posuere convallis a eget elit. Cras tristique sapien et ipsum feugiat consectetur. Cras ac ornare massa, sed dictum tortor. Duis ac vehicula quam. Pellentesque non sollicitudin ex. Proin ut porttitor nunc, non tempus sapien. Aenean maximus metus eget enim suscipit dignissim. In eu rhoncus eros. Proin condimentum facilisis diam quis suscipit.",
  },
  {
    id: 6,
    title: "Fizjoterapia ortopedyczna",
    date: "03-12-2022 - 5min",
    description:
      "Fusce fermentum et augue quis porta. Aenean interdum tincidunt posuere. Sed sed purus varius, tempus enim eu, lacinia mauris.",
    text: "Vestibulum sem enim, dictum eu diam sed, vulputate ultrices sem. Nullam nec lacus turpis. Fusce fermentum et augue quis porta. Aenean interdum tincidunt posuere. Sed sed purus varius, tempus enim eu, lacinia mauris. Pellentesque ac lacus dignissim, ultrices magna sit amet, pretium eros. Integer eget feugiat odio. Suspendisse aliquet a eros in auctor. Sed fermentum blandit massa nec imperdiet. Proin eu nisl libero. Morbi sit amet lectus aliquet, aliquam erat ac, rhoncus justo. Sed vestibulum, metus ut dapibus convallis, purus felis pretium metus, sit amet blandit felis nisi vel neque. In ac purus risus. Vivamus at erat mi. Nullam blandit sapien mi, quis congue lacus sollicitudin quis. Nunc eget velit auctor diam maximus fermentum. In lorem felis, sollicitudin et tincidunt eu, porttitor ac dui. Quisque condimentum, lacus ac ultricies dignissim, tortor magna condimentum eros, nec sagittis erat elit nec leo. Sed viverra tincidunt ante ac maximus. Cras sed leo tortor. Sed ultricies interdum est, ac hendrerit tortor blandit eget. In faucibus varius leo, in ornare lacus rutrum eu. Praesent quis ex non elit rhoncus tempor ac vitae velit. Curabitur placerat lacus et massa tempor ullamcorper. Nulla molestie condimentum nibh, a ullamcorper arcu tempus vitae. Aenean in mi viverra turpis posuere convallis a eget elit. Cras tristique sapien et ipsum feugiat consectetur. Cras ac ornare massa, sed dictum tortor. Duis ac vehicula quam. Pellentesque non sollicitudin ex. Proin ut porttitor nunc, non tempus sapien. Aenean maximus metus eget enim suscipit dignissim. In eu rhoncus eros. Proin condimentum facilisis diam quis suscipit.",
  },
  {
    id: 7,
    title: "Fizjoterapia ortopedyczna",
    date: "03-12-2022 - 5min",
    description:
      "Fusce fermentum et augue quis porta. Aenean interdum tincidunt posuere. Sed sed purus varius, tempus enim eu, lacinia mauris.",
    text: "Vestibulum sem enim, dictum eu diam sed, vulputate ultrices sem. Nullam nec lacus turpis. Fusce fermentum et augue quis porta. Aenean interdum tincidunt posuere. Sed sed purus varius, tempus enim eu, lacinia mauris. Pellentesque ac lacus dignissim, ultrices magna sit amet, pretium eros. Integer eget feugiat odio. Suspendisse aliquet a eros in auctor. Sed fermentum blandit massa nec imperdiet. Proin eu nisl libero. Morbi sit amet lectus aliquet, aliquam erat ac, rhoncus justo. Sed vestibulum, metus ut dapibus convallis, purus felis pretium metus, sit amet blandit felis nisi vel neque. In ac purus risus. Vivamus at erat mi. Nullam blandit sapien mi, quis congue lacus sollicitudin quis. Nunc eget velit auctor diam maximus fermentum. In lorem felis, sollicitudin et tincidunt eu, porttitor ac dui. Quisque condimentum, lacus ac ultricies dignissim, tortor magna condimentum eros, nec sagittis erat elit nec leo. Sed viverra tincidunt ante ac maximus. Cras sed leo tortor. Sed ultricies interdum est, ac hendrerit tortor blandit eget. In faucibus varius leo, in ornare lacus rutrum eu. Praesent quis ex non elit rhoncus tempor ac vitae velit. Curabitur placerat lacus et massa tempor ullamcorper. Nulla molestie condimentum nibh, a ullamcorper arcu tempus vitae. Aenean in mi viverra turpis posuere convallis a eget elit. Cras tristique sapien et ipsum feugiat consectetur. Cras ac ornare massa, sed dictum tortor. Duis ac vehicula quam. Pellentesque non sollicitudin ex. Proin ut porttitor nunc, non tempus sapien. Aenean maximus metus eget enim suscipit dignissim. In eu rhoncus eros. Proin condimentum facilisis diam quis suscipit.",
  },
  {
    id: 8,
    title: "Fizjoterapia ortopedyczna",
    date: "03-12-2022 - 5min",
    description:
      "Fusce fermentum et augue quis porta. Aenean interdum tincidunt posuere. Sed sed purus varius, tempus enim eu, lacinia mauris.",
    text: "Vestibulum sem enim, dictum eu diam sed, vulputate ultrices sem. Nullam nec lacus turpis. Fusce fermentum et augue quis porta. Aenean interdum tincidunt posuere. Sed sed purus varius, tempus enim eu, lacinia mauris. Pellentesque ac lacus dignissim, ultrices magna sit amet, pretium eros. Integer eget feugiat odio. Suspendisse aliquet a eros in auctor. Sed fermentum blandit massa nec imperdiet. Proin eu nisl libero. Morbi sit amet lectus aliquet, aliquam erat ac, rhoncus justo. Sed vestibulum, metus ut dapibus convallis, purus felis pretium metus, sit amet blandit felis nisi vel neque. In ac purus risus. Vivamus at erat mi. Nullam blandit sapien mi, quis congue lacus sollicitudin quis. Nunc eget velit auctor diam maximus fermentum. In lorem felis, sollicitudin et tincidunt eu, porttitor ac dui. Quisque condimentum, lacus ac ultricies dignissim, tortor magna condimentum eros, nec sagittis erat elit nec leo. Sed viverra tincidunt ante ac maximus. Cras sed leo tortor. Sed ultricies interdum est, ac hendrerit tortor blandit eget. In faucibus varius leo, in ornare lacus rutrum eu. Praesent quis ex non elit rhoncus tempor ac vitae velit. Curabitur placerat lacus et massa tempor ullamcorper. Nulla molestie condimentum nibh, a ullamcorper arcu tempus vitae. Aenean in mi viverra turpis posuere convallis a eget elit. Cras tristique sapien et ipsum feugiat consectetur. Cras ac ornare massa, sed dictum tortor. Duis ac vehicula quam. Pellentesque non sollicitudin ex. Proin ut porttitor nunc, non tempus sapien. Aenean maximus metus eget enim suscipit dignissim. In eu rhoncus eros. Proin condimentum facilisis diam quis suscipit.",
  },
  {
    id: 9,
    title: "Fizjoterapia ortopedyczna",
    date: "03-12-2022 - 5min",
    description:
      "Fusce fermentum et augue quis porta. Aenean interdum tincidunt posuere. Sed sed purus varius, tempus enim eu, lacinia mauris.",
    text: "Vestibulum sem enim, dictum eu diam sed, vulputate ultrices sem. Nullam nec lacus turpis. Fusce fermentum et augue quis porta. Aenean interdum tincidunt posuere. Sed sed purus varius, tempus enim eu, lacinia mauris. Pellentesque ac lacus dignissim, ultrices magna sit amet, pretium eros. Integer eget feugiat odio. Suspendisse aliquet a eros in auctor. Sed fermentum blandit massa nec imperdiet. Proin eu nisl libero. Morbi sit amet lectus aliquet, aliquam erat ac, rhoncus justo. Sed vestibulum, metus ut dapibus convallis, purus felis pretium metus, sit amet blandit felis nisi vel neque. In ac purus risus. Vivamus at erat mi. Nullam blandit sapien mi, quis congue lacus sollicitudin quis. Nunc eget velit auctor diam maximus fermentum. In lorem felis, sollicitudin et tincidunt eu, porttitor ac dui. Quisque condimentum, lacus ac ultricies dignissim, tortor magna condimentum eros, nec sagittis erat elit nec leo. Sed viverra tincidunt ante ac maximus. Cras sed leo tortor. Sed ultricies interdum est, ac hendrerit tortor blandit eget. In faucibus varius leo, in ornare lacus rutrum eu. Praesent quis ex non elit rhoncus tempor ac vitae velit. Curabitur placerat lacus et massa tempor ullamcorper. Nulla molestie condimentum nibh, a ullamcorper arcu tempus vitae. Aenean in mi viverra turpis posuere convallis a eget elit. Cras tristique sapien et ipsum feugiat consectetur. Cras ac ornare massa, sed dictum tortor. Duis ac vehicula quam. Pellentesque non sollicitudin ex. Proin ut porttitor nunc, non tempus sapien. Aenean maximus metus eget enim suscipit dignissim. In eu rhoncus eros. Proin condimentum facilisis diam quis suscipit.",
  },
];

export default services;
